[package]
name = "ccommon_fn"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Wdk_Foundation"
]}
